export const MAX_MAINTENANCE_CATEGORY_NAME_LENGTH = 30;
export const MAX_MAINTENANCE_NOTES_LENGTH = 500;
export const MAX_MAINTENANCE_COST = 9_999_999;
export const MIN_MAINTENANCE_COST = 0;
export const MAX_MAINTENANCE_INTERVAL_KM = 500_000;
export const MIN_MAINTENANCE_INTERVAL_KM = 1;
export const MAX_MAINTENANCE_INTERVAL_DAYS = 3_650;
export const MIN_MAINTENANCE_INTERVAL_DAYS = 1;
